[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"


[window]
opacity = 0.7


[colors.primary]
background = '#24273A' # base
foreground = '#CAD3F5' # text
dim_foreground = '#CAD3F5' # text
bright_foreground = '#CAD3F5' # text


[colors.cursor]
text = '#24273A' # base
cursor = '#F4DBD6' # rosewater


[colors.vi_mode_cursor]
text = '#24273A' # base
cursor = '#B7BDF8' # lavender


[colors.search.matches]
foreground = '#24273A' # base
background = '#A5ADCB' # subtext0


[colors.search.focused_match]
foreground = '#24273A' # base
background = '#A6DA95' # green


[colors.footer_bar]
foreground = '#24273A' # base
background = '#A5ADCB' # subtext0


[colors.hints.start]
foreground = '#24273A' # base
background = '#EED49F' # yellow


[colors.hints.end]
foreground = '#24273A' # base
background = '#A5ADCB' # subtext0


[colors.selection]
text = '#24273A' # base
background = '#F4DBD6' # rosewater


[colors.normal]
black = '#494D64' # surface1
red = '#ED8796' # red
green = '#A6DA95' # green
yellow = '#EED49F' # yellow
blue = '#8AADF4' # blue
magenta = '#F5BDE6' # pink
cyan = '#8BD5CA' # teal
white = '#B8C0E0' # subtext1


[colors.bright]
black = '#5B6078' # surface2
red = '#ee99a0' # maroon
green = '#b8e1aa' # bright green
yellow = '#f1ddb2' # bright yellow
blue = '#7dc4e4' # sapphire
magenta = '#f7caeb' # bright pink
cyan = '#91d7e3' # sky
white = '#A5ADCB' # subtext0


[colors.dim]
black = '#494D64' # surface1
red = '#ED8796' # red
green = '#A6DA95' # green
yellow = '#EED49F' # yellow
blue = '#8AADF4' # blue
magenta = '#F5BDE6' # pink
cyan = '#8BD5CA' # teal
white = '#B8C0E0' # subtext1

